### ISSUE TITLE
Derive Debug For TokenManager Struct.

### ISSUE THREAD

**Issue by Iamdavidonuh** [ywegel/oauth_fcm#20]
I'm wondering  if `TokenManager` could derive essential traits such as Debug and maybe serde::Serialize and serde::Deserialize.

**Comment by ywegel** [comment]
I think I did not derive debug for the TokenManager so that no one could accidentally log the token, thus exposing sensitive data. What is your use case for needing this? Would it be enough for you to have a custom debug implementation where the token and service account are redacted from the debug output, and only non-sensitive data is exposed?

**Comment by Iamdavidonuh** [comment]
Ah, I completely missed that. My use case involves including the token manager as part of a larger struct, and the issue arose because it derived `Debug`. A custom debug implementation would definitely work for this

**Comment by ywegel** [comment]
Thank you for your merge request. I have created an on demand release for you: [0.3.0](https://crates.io/crates/oauth_fcm/0.3.0)
